{% set name = "pypher" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypher-{{ version }}.tar.gz
  sha256: 988468b17490f03332832d8641240aaf4016b4cc8fcac7ebdb85166e5827e375

build:
  entry_points:
    - pypher = pypher.pypher:main
    - addpixscl = pypher.addpixscl:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - setuptools
    - python {{ python_min }}
  run:
    - astropy-base >=2.0
    - numpy >=1.7.2
    - python >={{ python_min }}
    - scipy >=0.9

test:
  imports:
    - pypher
  commands:
    - pip check
    - pypher --help
    - addpixscl --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://pypher.readthedocs.org/en/latest/
  summary: Python-based PSF Homogenization kERnels production
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aboucaud
    - goanpeca
