{% set name = "pypher" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypher-{{ version }}.tar.gz
  sha256: fc11caaf6cf15b4b31ef496359b2fb8aa9faf8a9b3da6ceca6fafbff78e1a9f4

build:
  entry_points:
    - pypher = pypher.pypher:main
    - addpixscl = pypher.addpixscl:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - astropy >=2.0
    - numpy >=1.7.2
    - python >=3.6
    - scipy >=0.9

test:
  imports:
    - pypher
  commands:
    - pip check
    - pypher --help
    - addpixscl --help
  requires:
    - pip

about:
  home: http://pypher.readthedocs.org/en/latest/
  summary: Python-based PSF Homogenization kERnels production
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - aboucaud
    - goanpeca
